name: Ubuntu
on:
  watch:
    types: started
jobs:
  GoogleDrive:
    runs-on: ubuntu-latest
    steps:
    - name: 配置
      run: curl https://raw.githubusercontent.com/damifen/-/master/g.sh | sudo bash
    - name: root
      run: cd /root
    - name: 转存
      run: gclone copy gc:{0ALcGBTZr55T8Uk9PVA} gc:{0ALEG42D9Nq7IUk9PVA}  --drive-server-side-across-configs --transfers=20
